/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project5;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aryaa
 */
public class modul5 extends javax.swing.JFrame {
    DefaultComboBoxModel<String> modelcb = new DefaultComboBoxModel<>();
    int hargaBarang;
   
    /**
     * Creates new form modul5
     */
    public modul5() {
        initComponents();
        cbbarang.setModel(modelcb);
        modelcb.addElement("--- Pilih Barang ---");
        fillComboBox();
        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fdata = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fkodebarang1 = new javax.swing.JTextField();
        fnamapembeli1 = new javax.swing.JTextField();
        ftotalharga1 = new javax.swing.JTextField();
        fkembali1 = new javax.swing.JTextField();
        fkodepembeli1 = new javax.swing.JTextField();
        fhargabarang1 = new javax.swing.JTextField();
        fjumlahbeli1 = new javax.swing.JTextField();
        ftotalpembayaran1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnupdate1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        barang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbbarang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fkodebarang = new javax.swing.JTextField();
        fnamapembeli = new javax.swing.JTextField();
        ftotalharga = new javax.swing.JTextField();
        fkembali = new javax.swing.JTextField();
        fkodepembeli = new javax.swing.JTextField();
        fhargabarang = new javax.swing.JTextField();
        fjumlahbeli = new javax.swing.JTextField();
        ftotalpembayaran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        fhitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(124, 157, 150));
        jTabbedPane1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(233, 179, 132));

        jScrollPane1.setBackground(new java.awt.Color(244, 242, 222));

        fdata.setBackground(new java.awt.Color(244, 242, 222));
        fdata.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        fdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pembeli", "Kode Barang", "Nama Barang", "Harga Barang", "Nama Pembeli", "Jumlah Beli", "Total Harga", "Total Pembayaran", "Kembalian"
            }
        ));
        fdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fdata);

        jInternalFrame1.setBackground(new java.awt.Color(161, 204, 209));
        jInternalFrame1.setVisible(true);

        jPanel5.setBackground(new java.awt.Color(161, 204, 209));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        jLabel3.setText("Kode Pembeli");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, 30));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel10.setText("Kode Barang");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 30));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel11.setText("Harga Barang");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, 30));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel12.setText("Jumlah Pembeli");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 30));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel13.setText("Nama Pembeli");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 30));

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel14.setText("Total Harga");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 20));

        jLabel15.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        jLabel15.setText("Total Pembayaran");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 106, -1));

        fkodebarang1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(fkodebarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 210, 40));

        fnamapembeli1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(fnamapembeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 210, 40));

        ftotalharga1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(ftotalharga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, 40));

        fkembali1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(fkembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 210, 40));

        fkodepembeli1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(fkodepembeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 210, 40));

        fhargabarang1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(fhargabarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 220, 30));

        fjumlahbeli1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(fjumlahbeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 220, 30));

        ftotalpembayaran1.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(ftotalpembayaran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 220, 30));

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel16.setText("Kembalian");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, 20));

        btnupdate1.setBackground(new java.awt.Color(124, 157, 150));
        btnupdate1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnupdate1.setText("Update");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 110, 40));

        btndelete1.setBackground(new java.awt.Color(124, 157, 150));
        btndelete1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btndelete1.setText("Delete");
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });
        jPanel5.add(btndelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 100, 40));

        barang.setBackground(new java.awt.Color(244, 242, 222));
        jPanel5.add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 50));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Penjualan", jPanel1);

        jPanel2.setBackground(new java.awt.Color(233, 179, 132));

        jPanel3.setBackground(new java.awt.Color(233, 179, 132));

        cbbarang.setBackground(new java.awt.Color(161, 204, 209));
        cbbarang.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        cbbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "MEJA", "KURSI" }));
        cbbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbarangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        jLabel1.setText("Kode Pembeli");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setText("Kode Barang");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setText("Harga Barang");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setText("Jumlah Pembeli");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setText("Nama Pembeli");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setText("Total Harga");

        jLabel8.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        jLabel8.setText("Total Pembayaran");

        fkodebarang.setBackground(new java.awt.Color(244, 242, 222));

        fnamapembeli.setBackground(new java.awt.Color(244, 242, 222));

        ftotalharga.setBackground(new java.awt.Color(244, 242, 222));

        fkembali.setBackground(new java.awt.Color(244, 242, 222));

        fkodepembeli.setBackground(new java.awt.Color(244, 242, 222));

        fhargabarang.setBackground(new java.awt.Color(244, 242, 222));

        fjumlahbeli.setBackground(new java.awt.Color(244, 242, 222));

        ftotalpembayaran.setBackground(new java.awt.Color(244, 242, 222));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel9.setText("Kembalian");

        btnsimpan.setBackground(new java.awt.Color(124, 157, 150));
        btnsimpan.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(124, 157, 150));
        btnreset.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        fhitung.setBackground(new java.awt.Color(124, 157, 150));
        fhitung.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        fhitung.setText("Hitung");
        fhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(fkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(fhargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(fnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(ftotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(fkodepembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(fhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftotalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 15, Short.MAX_VALUE)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fhargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftotalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(fkodepembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Data Inputan", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbarangActionPerformed
        // TODO add your handling code here:
        String selectedBarang = (String) cbbarang.getSelectedItem();
        try {
            java.sql.Connection conn = project5.PROJECT5.koneksiDB();
            String query = "SELECT kode_barang, harga_barang FROM data_barang WHERE nama_barang = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, selectedBarang);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                fkodebarang.setText(rs.getString("kode_barang"));
                hargaBarang = rs.getInt("harga_barang");
                fhargabarang.setText(String.valueOf(hargaBarang));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbbarangActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
          try{
            String sql = "insert into data_pembeli values('"+fkodepembeli.getText()+"', '"+fkodebarang.getText()+"', '"+cbbarang.getSelectedItem()+"', '"+fhargabarang.getText()+"', '"+fnamapembeli.getText()+"', '"+fjumlahbeli.getText()+"', '"+ftotalharga.getText()+"', '"+ftotalpembayaran.getText()+"', '"+fkembali.getText()+"')";
            java.sql.Connection conn = (java.sql.Connection) project5.PROJECT5.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            btnresetActionPerformed(evt);
            tampil_data();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        fkodepembeli.setText("");
        fkodebarang.setText("");
        fhargabarang.setText("");
        fnamapembeli.setText("");
        fjumlahbeli.setText("");
        ftotalharga.setText("");
        ftotalpembayaran.setText("");
        fkembali.setText("");
        cbbarang.setSelectedIndex(0);
    }//GEN-LAST:event_btnresetActionPerformed
 private void fillComboBox() {
        try {
            // Buat koneksi ke database
            java.sql.Connection conn = project5.PROJECT5.koneksiDB();
            // Buat query SQL untuk mengambil data
            String query = "SELECT nama_barang FROM data_barang";
            
            // Persiapkan statement SQL
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            
            // Eksekusi query
            ResultSet rs = pst.executeQuery();
            
            // Isi combobox dengan data dari database
            while (rs.next()) {
                String item = rs.getString(1); 
            // 1 adalah indeks kolom data yang akan diambil
                if (!containsItem(item)) {
                    modelcb.addElement(item);
                }
            }
            
            // Tutup koneksi dan resource
            rs.close();
            pst.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }   
    }
 private boolean containsItem(String item) {
        for (int i = 0; i < modelcb.getSize(); i++) {
            if (modelcb.getElementAt(i).equals(item)) {
                return true;
            }
        }
        return false;
    }
    private void fhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhitungActionPerformed
         if (fjumlahbeli.getText().isEmpty() || ftotalpembayaran.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Jumlah Pembelian dan Jumlah Pembayaran Dengan Benar", "Tidak Boleh Kosong", JOptionPane.ERROR_MESSAGE);
        }else{
            int jumlahbeli = Integer.parseInt(fjumlahbeli.getText());
            int totalharga = hargaBarang * jumlahbeli;
            int totalbayar = Integer.parseInt(ftotalpembayaran.getText());
            int kembalian = totalbayar - totalharga;
            ftotalharga.setText(Integer.toString(totalharga));
            fkembali.setText(Integer.toString(kembalian));
        }
    }//GEN-LAST:event_fhitungActionPerformed

    private void fdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdataMouseClicked
        // TODO add your handling code here:
         DefaultTableModel modeldata = (DefaultTableModel) fdata.getModel();
        int selectedRow = fdata.getSelectedRow();
        if (selectedRow != -1) { // Pastikan baris yang dipilih valid
            fkodepembeli1.setText(modeldata.getValueAt(selectedRow, 0).toString()); // Kolom 1 (Kode Pembelian)
            fkodebarang1.setText(modeldata.getValueAt(selectedRow, 1).toString()); // Kolom 2 (Kode Barang)
            barang.setText(modeldata.getValueAt(selectedRow, 2).toString());
            fhargabarang1.setText(modeldata.getValueAt(selectedRow, 3).toString());
            // Isi teksfield lainnya sesuai dengan kolom yang sesuai
            fnamapembeli1.setText(modeldata.getValueAt(selectedRow, 4).toString()); // Kolom 5 (Nama Pembeli)
            fjumlahbeli1.setText(modeldata.getValueAt(selectedRow, 5).toString()); // Kolom 6 (Jumlah Pembelian)
            ftotalharga1.setText(modeldata.getValueAt(selectedRow, 6).toString()); // Kolom 7 (Total Harga)
            ftotalpembayaran1.setText(modeldata.getValueAt(selectedRow, 7).toString()); // Kolom 8 (Total Pembayaran)
            fkembali1.setText(modeldata.getValueAt(selectedRow, 8).toString()); // Kolom 9 (Kembalian)
        }
    }//GEN-LAST:event_fdataMouseClicked

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        // TODO add your handling code here:
           DefaultTableModel modeldata = (DefaultTableModel) fdata.getModel();
        int selectedRow = fdata.getSelectedRow();
        if (selectedRow != -1){
            try{
                String sql = "UPDATE data_pembeli SET kode_pembelian = '"+fkodepembeli1.getText()+"', kode_barang = '"+fkodebarang1.getText()+"',"
                        + "nama_barang = '"+barang.getText()+"', harga_barang = '"+fhargabarang1.getText()+"', "
                        + "nama_pembeli = '"+fnamapembeli1.getText()+"', jumlah_pembeli = '"+fjumlahbeli1.getText()+"', "
                        + "total_harga = '"+ftotalharga1.getText()+"', total_pembayaran = '"+ftotalpembayaran1.getText()+"', "
                        + "kembalian = '"+fkembali1.getText()+"' WHERE kode_pembelian = '"+modeldata.getValueAt(selectedRow, 0)+"'";
                java.sql.Connection conn = (java.sql.Connection)project5.PROJECT5.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Berhasil Diupdate");
                tampil_data();
                fkodepembeli1.setText("");
                fkodebarang1.setText("");
                fhargabarang1.setText("");
                fnamapembeli1.setText("");
                fjumlahbeli1.setText("");
                ftotalharga1.setText("");
                ftotalpembayaran1.setText("");
                fkembali1.setText("");
                barang.setText("");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Diupdate");
                System.out.println(e.getMessage());
            }
        }else{
        JOptionPane.showMessageDialog(null, "Silakan pilih data terlebih dahulu");
        }
    }//GEN-LAST:event_btnupdate1ActionPerformed
    public void tampil_data(){
        DefaultTableModel tabeldata = new DefaultTableModel();
        tabeldata.addColumn("Kode Pembelian");
        tabeldata.addColumn("Kode Barang");
        tabeldata.addColumn("Nama Barang");
        tabeldata.addColumn("Harga Barang");
        tabeldata.addColumn("Nama Pembeli");
        tabeldata.addColumn("Jumlah Pembelian");
        tabeldata.addColumn("Total Harga");
        tabeldata.addColumn("Total Bayar");
        tabeldata.addColumn("Kembalian");
        
        try{
            java.sql.Connection conn = project5.PROJECT5.koneksiDB();
            String query = "select * from data_pembeli";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                Object[] row = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)};
                tabeldata.addRow(row);
            }
            fdata.setModel(tabeldata);
        }catch (Exception e){
            e.printStackTrace();
        }
    }    
        
        
    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeldata = (DefaultTableModel) fdata.getModel();
        int selectedRow = fdata.getSelectedRow();
        if (selectedRow != -1){
            try{
                String sql = "DELETE FROM data_pembeli WHERE kode_pembelian = '"+modeldata.getValueAt(selectedRow, 0)+"' ";
                java.sql.Connection conn = (java.sql.Connection)project5.PROJECT5.koneksiDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
                tampil_data();
                fkodepembeli1.setText("");
                fkodebarang1.setText("");
                fhargabarang1.setText("");
                fnamapembeli1.setText("");
                fjumlahbeli1.setText("");
                ftotalharga1.setText("");
                ftotalpembayaran1.setText("");
                fkembali1.setText("");
                barang.setText("");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Dihapus");
                System.out.println(e.getMessage());
            }
        }else{
        JOptionPane.showMessageDialog(null, "Silakan pilih data terlebih dahulu");
        }
    }//GEN-LAST:event_btndelete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barang;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JComboBox<String> cbbarang;
    private javax.swing.JTable fdata;
    private javax.swing.JTextField fhargabarang;
    private javax.swing.JTextField fhargabarang1;
    private javax.swing.JButton fhitung;
    private javax.swing.JTextField fjumlahbeli;
    private javax.swing.JTextField fjumlahbeli1;
    private javax.swing.JTextField fkembali;
    private javax.swing.JTextField fkembali1;
    private javax.swing.JTextField fkodebarang;
    private javax.swing.JTextField fkodebarang1;
    private javax.swing.JTextField fkodepembeli;
    private javax.swing.JTextField fkodepembeli1;
    private javax.swing.JTextField fnamapembeli;
    private javax.swing.JTextField fnamapembeli1;
    private javax.swing.JTextField ftotalharga;
    private javax.swing.JTextField ftotalharga1;
    private javax.swing.JTextField ftotalpembayaran;
    private javax.swing.JTextField ftotalpembayaran1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
